import { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle`
 /* #### Generated By: http://www.cufonfonts.com #### */

 @font-face {
    font-family: 'Assistant Regular';
    font-style: normal;
    font-weight: normal;
    src: local('Assistant Regular'), url('/fonts/assistant/Assistant-Regular.woff') format('woff');
    }
    
    

    @font-face {
    font-family: 'Assistant SemiBold';
    font-style: normal;
    font-weight: normal;
    src: local('Assistant SemiBold'), url('/fonts/assistant/Assistant-SemiBold.woff') format('woff');
    }
    

    @font-face {
    font-family: 'Assistant Bold';
    font-style: normal;
    font-weight: normal;
    src: local('Assistant Bold'), url('/fonts/assistant/Assistant-Bold.woff') format('woff');
    }
    
    

    @font-face {
    font-family: 'Segoe UI Regular';
    font-style: normal;
    font-family: sans-serif;
    font-weight: normal;
    src:  url('/fonts/segoe/Segoe UI.woff') format('woff');
    }
    
    @font-face {
    font-family: 'Segoe UI SemiBold';
    font-style: normal;
    font-weight: 600;
    src:  url('/fonts/segoe/Segoe UI.woff') format('woff');
    }


    @font-face {
    font-family: 'Segoe UI Bold';
    font-style: normal;
    font-weight: normal;
    src:  url('/fonts/segoe/Segoe UI Bold.woff') format('woff');
    }
  
  *,
  *::before,
  *::after {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
  }

  ul,
  ol {
    list-style: none;
  }

  a {
    text-decoration: none;
  }

  body {
    font-family: sans-serif;
    font-size: 16px;
  }

 
`;

export default GlobalStyle;
